layout_spectrum: 0
typography_spectrum: 0.3498134
color:
  saturation: 0.9881727
  lightness: 0.5727612
  brandStrength: 0.9729499
  rhythmicContrast: 0.2112873
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Benj Roberts
