layout_spectrum: 0
color:
  saturation: 0.8097015
  brandStrength: 1
  lightness: 0.6501865
  brandColors:
    - '#0167DF'
    - '#CBDBFD'
    - '#6D94B8'
    - '#676331'
    - '#F9F9BD'
  rhythmicContrast: 0.4221082
typography_spectrum: 0.3498134
name: Benj Roberts
